# Generated by Django 2.2 on 2021-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210523_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(upload_to='img/', verbose_name='Фотография'),
        ),
    ]
