# Generated by Django 2.2 on 2021-05-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210523_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='images',
            new_name='image',
        ),
    ]
